services:
  pgvector:
    container_name: gestionRagDb
    image: 'pgvector/pgvector:pg16'
    environment:
      - POSTGRES_DB=gestionRagDb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    volumes:
      - agentic_rag_chatbot_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - agentic-chatbot-net



  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
volumes:
    agentic_rag_chatbot_data:

networks:
    agentic-chatbot-net:
      driver: bridge